name: voc
description: An implementation of the c3voc's API for media.ccc.de
version: 0.0.1
homepage: https://github.com/Ampless/voc.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  schttp: ^3.2.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
