name: voc
description: An implementation of the c3voc's API for media.ccc.de
version: 0.0.4
homepage: https://github.com/Ampless/voc.dart

environment:
  sdk: ^3.0.0

dependencies:
  schttp: ^5.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
